import { Video, User } from '@/types';

export const mockUser: User = {
  id: '1',
  email: 'user@example.com',
  name: 'Demo User',
  credits: 50,
  createdAt: new Date('2024-01-01'),
};

export const mockVideos: Video[] = [
  {
    id: '1',
    title: 'Futuristic City at Sunset',
    description: 'A breathtaking view of a futuristic cityscape during golden hour',
    prompt: 'futuristic city skyline at sunset with flying cars',
    thumbnailUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=80',
    videoUrl: 'https://example.com/video1.mp4',
    duration: 30,
    views: 1250,
    likes: 89,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-11-10'),
    status: 'completed',
  },
  {
    id: '2',
    title: 'Underwater Ocean Life',
    description: 'Explore the vibrant colors of coral reefs and marine life',
    prompt: 'underwater coral reef with colorful fish swimming',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    videoUrl: 'https://example.com/video2.mp4',
    duration: 45,
    views: 2340,
    likes: 156,
    creatorId: '2',
    creatorName: 'Ocean Explorer',
    createdAt: new Date('2024-11-09'),
    status: 'completed',
  },
  {
    id: '3',
    title: 'Space Journey',
    description: 'Travel through the cosmos and witness distant galaxies',
    prompt: 'journey through space with stars and galaxies',
    thumbnailUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&q=80',
    videoUrl: 'https://example.com/video3.mp4',
    duration: 60,
    views: 3450,
    likes: 234,
    creatorId: '3',
    creatorName: 'Space Voyager',
    createdAt: new Date('2024-11-08'),
    status: 'completed',
  },
  {
    id: '4',
    title: 'Mountain Sunrise',
    description: 'Watch the sun rise over majestic mountain peaks',
    prompt: 'sunrise over snow-capped mountains with clouds',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    videoUrl: 'https://example.com/video4.mp4',
    duration: 40,
    views: 1890,
    likes: 145,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-11-07'),
    status: 'completed',
  },
  {
    id: '5',
    title: 'Forest Meditation',
    description: 'A peaceful walk through an enchanted forest',
    prompt: 'serene forest path with sunlight filtering through trees',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=800&q=80',
    videoUrl: 'https://example.com/video5.mp4',
    duration: 35,
    views: 980,
    likes: 67,
    creatorId: '4',
    creatorName: 'Nature Lover',
    createdAt: new Date('2024-11-06'),
    status: 'completed',
  },
  {
    id: '6',
    title: 'Desert Dreams',
    description: 'Experience the vast beauty of sand dunes at dusk',
    prompt: 'rolling sand dunes in desert at golden hour',
    thumbnailUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=800&q=80',
    videoUrl: 'https://example.com/video6.mp4',
    duration: 50,
    views: 1560,
    likes: 98,
    creatorId: '5',
    creatorName: 'Desert Wanderer',
    createdAt: new Date('2024-11-05'),
    status: 'completed',
  },
];
