import { Video, User } from '@/types';

export const mockUser: User = {
  id: '1',
  email: 'user@example.com',
  name: 'Demo User',
  credits: 50,
  createdAt: new Date('2024-01-01'),
};

export const mockVideos: Video[] = [
  {
    id: '1',
    title: 'Futuristic City at Sunset',
    description: 'A breathtaking view of a futuristic cityscape during golden hour',
    prompt: 'futuristic city skyline at sunset with flying cars',
    thumbnailUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=80',
    videoUrl: 'https://example.com/video1.mp4',
    duration: 30,
    views: 1250,
    likes: 89,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-11-10'),
    status: 'completed',
    aspectRatio: '16:9',
  },
  {
    id: '2',
    title: 'Underwater Ocean Life',
    description: 'Explore the vibrant colors of coral reefs and marine life',
    prompt: 'underwater coral reef with colorful fish swimming',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    videoUrl: 'https://example.com/video2.mp4',
    duration: 45,
    views: 2340,
    likes: 156,
    creatorId: '2',
    creatorName: 'Ocean Explorer',
    createdAt: new Date('2024-11-09'),
    status: 'completed',
    aspectRatio: '9:16',
  },
  {
    id: '3',
    title: 'Space Journey',
    description: 'Travel through the cosmos and witness distant galaxies',
    prompt: 'journey through space with stars and galaxies',
    thumbnailUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&q=80',
    videoUrl: 'https://example.com/video3.mp4',
    duration: 60,
    views: 3450,
    likes: 234,
    creatorId: '3',
    creatorName: 'Space Voyager',
    createdAt: new Date('2024-11-08'),
    status: 'completed',
    aspectRatio: '1:1',
  },
  {
    id: '4',
    title: 'Mountain Sunrise',
    description: 'Watch the sun rise over majestic mountain peaks',
    prompt: 'sunrise over snow-capped mountains with clouds',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    videoUrl: 'https://example.com/video4.mp4',
    duration: 40,
    views: 1890,
    likes: 145,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-11-07'),
    status: 'completed',
    aspectRatio: '16:9',
  },
  {
    id: '5',
    title: 'Forest Meditation',
    description: 'A peaceful walk through an enchanted forest',
    prompt: 'serene forest path with sunlight filtering through trees',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=800&q=80',
    videoUrl: 'https://example.com/video5.mp4',
    duration: 35,
    views: 980,
    likes: 67,
    creatorId: '4',
    creatorName: 'Nature Lover',
    createdAt: new Date('2024-11-06'),
    status: 'completed',
    aspectRatio: '9:16',
  },
  {
    id: '6',
    title: 'Desert Dreams',
    description: 'Experience the vast beauty of sand dunes at dusk',
    prompt: 'rolling sand dunes in desert at golden hour',
    thumbnailUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=800&q=80',
    videoUrl: 'https://example.com/video6.mp4',
    duration: 50,
    views: 1560,
    likes: 98,
    creatorId: '5',
    creatorName: 'Desert Wanderer',
    createdAt: new Date('2024-11-05'),
    status: 'completed',
    aspectRatio: '1:1',
  },
  {
    id: '7',
    title: 'Northern Lights Dance',
    description: 'Aurora borealis illuminating the arctic sky',
    prompt: 'northern lights aurora borealis dancing in night sky',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=800&q=80',
    videoUrl: 'https://example.com/video7.mp4',
    duration: 55,
    views: 4200,
    likes: 312,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-11-04'),
    status: 'completed',
    aspectRatio: '16:9',
  },
  {
    id: '8',
    title: 'Tokyo Neon Streets',
    description: 'Vibrant city life in downtown Tokyo at night',
    prompt: 'tokyo street at night with neon signs and crowds',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    videoUrl: 'https://example.com/video8.mp4',
    duration: 25,
    views: 2890,
    likes: 201,
    creatorId: '6',
    creatorName: 'Urban Explorer',
    createdAt: new Date('2024-11-03'),
    status: 'completed',
    aspectRatio: '9:16',
  },
  {
    id: '9',
    title: 'Waterfall Paradise',
    description: 'Majestic waterfall cascading through lush rainforest',
    prompt: 'large waterfall in tropical rainforest with mist',
    thumbnailUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80',
    videoUrl: 'https://example.com/video9.mp4',
    duration: 40,
    views: 1670,
    likes: 128,
    creatorId: '2',
    creatorName: 'Ocean Explorer',
    createdAt: new Date('2024-11-02'),
    status: 'completed',
    aspectRatio: '9:16',
  },
  {
    id: '10',
    title: 'Vintage Cafe Vibes',
    description: 'Cozy coffee shop atmosphere with warm lighting',
    prompt: 'cozy vintage cafe interior with warm lights',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    videoUrl: 'https://example.com/video10.mp4',
    duration: 30,
    views: 920,
    likes: 74,
    creatorId: '7',
    creatorName: 'Cafe Curator',
    createdAt: new Date('2024-11-01'),
    status: 'completed',
    aspectRatio: '1:1',
  },
  {
    id: '11',
    title: 'Cyberpunk Metropolis',
    description: 'Futuristic cityscape with holographic advertisements',
    prompt: 'cyberpunk city with neon holograms and flying vehicles',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    videoUrl: 'https://example.com/video11.mp4',
    duration: 45,
    views: 5340,
    likes: 445,
    creatorId: '3',
    creatorName: 'Space Voyager',
    createdAt: new Date('2024-10-31'),
    status: 'completed',
    aspectRatio: '16:9',
  },
  {
    id: '12',
    title: 'Zen Garden Meditation',
    description: 'Peaceful Japanese zen garden with raked sand',
    prompt: 'zen garden with rocks and raked sand patterns',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80',
    videoUrl: 'https://example.com/video12.mp4',
    duration: 35,
    views: 1120,
    likes: 93,
    creatorId: '4',
    creatorName: 'Nature Lover',
    createdAt: new Date('2024-10-30'),
    status: 'completed',
    aspectRatio: '1:1',
  },
  {
    id: '13',
    title: 'Surfer at Golden Hour',
    description: 'Surfer riding waves during sunset',
    prompt: 'surfer on wave at sunset with orange sky',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800&q=80',
    videoUrl: 'https://example.com/video13.mp4',
    duration: 20,
    views: 3210,
    likes: 267,
    creatorId: '8',
    creatorName: 'Beach Life',
    createdAt: new Date('2024-10-29'),
    status: 'completed',
    aspectRatio: '9:16',
  },
  {
    id: '14',
    title: 'Ancient Temple Ruins',
    description: 'Mystical ancient temple covered in jungle vines',
    prompt: 'ancient temple ruins in jungle with sunbeams',
    thumbnailUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    videoUrl: 'https://example.com/video14.mp4',
    duration: 50,
    views: 2450,
    likes: 189,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-10-28'),
    status: 'completed',
    aspectRatio: '16:9',
  },
  {
    id: '15',
    title: 'Abstract Art Flow',
    description: 'Colorful abstract paint swirling and mixing',
    prompt: 'abstract colorful paint flowing and mixing',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80',
    videoUrl: 'https://example.com/video15.mp4',
    duration: 15,
    views: 1780,
    likes: 142,
    creatorId: '9',
    creatorName: 'Art Visionary',
    createdAt: new Date('2024-10-27'),
    status: 'completed',
    aspectRatio: '1:1',
  },
  {
    id: '16',
    title: 'Snowy Mountain Peak',
    description: 'Drone shot of snow-covered mountain summit',
    prompt: 'aerial view of snowy mountain peak with clouds',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    videoUrl: 'https://example.com/video16.mp4',
    duration: 38,
    views: 2980,
    likes: 221,
    creatorId: '1',
    creatorName: 'Demo User',
    createdAt: new Date('2024-10-26'),
    status: 'completed',
    aspectRatio: '9:16',
  },
];
